# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 365367d20afaa3c55607251dd81dc384fecc90c451afb64c9029ed8fdc1b83e257cc7be6f5f8079f885706ea43675e529b1f703f77a03429588c053287fcd2a6

test:
  secret_key_base: efaa62f877c3cfcefaab0db6596f604a42b89c44be85663907afc88fb348558574412aa0b49f77ffc40d6abb1ce3d619d0839ac064db680a399bfb1c4cc08dd3

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
